Update onOrientationChanged for Android to identify the 4 main orientations.
PeterStaev/nativescript-image-swipe pull request #34
Opened 2019-02-20 20:07 UTC by socalrunner

I am suggesting 2 changes.

1. preloadedImageView assignment looks like it was duplicated, I removed the duplicate.
2. onOrientationChanged is resetting the zoomImageView every time the device is moved 1 degree in either axis.  Orientation is changing by the degree, but actual orientation change should be detected more coarsely.  My suggested change is to capture the actual orientation change based on 4 preset orientations, portrait, landscape, portrait-reversed, landscape-reversed and only reset the zoomImageView on those captured changes.

In the future, may we can add image rotation using this methodology.

Please let me know if you have any questions or suggestions.

Thank you!

Justin

2019-02-20 22:52 UTC, PeterStaev requested changes

2019-02-20 22:52 UTC, PeterStaev commented on image-swipe.android.ts
> -        }
This is not a duplicate. The previous one preloads `index -1` and this one preloads `index+1`

2019-02-20 22:52 UTC, PeterStaev commented on image-swipe.android.ts
> +            // ToDo: Rotate the image based on currentOrientation?
Not sure what do you mean with this TODO. Currently the image rotates as the phone rotates to the next orientation.

2019-02-21 06:50 UTC, PeterStaev requested changes

2019-02-21 06:50 UTC, PeterStaev commented on image-swipe.android.ts
> +const ORIENTATION_LANDSCAPE_REVERSE = 3;
Lets make these a const enum  for lower transpiled size:
```ts
const enum Orientation {
    Portrait = 0,
    Landscape = 1,
    PortraitReverse = 2,
    LandscapeReverse = 3,
}
```

2019-02-21 19:00 UTC, PeterStaev approved these changes

2019-02-25 22:10 UTC, socalrunner commented
Hi @PeterStaev, I hope you are doing well.  I was just checking in to find out when you plan to merge this PR so that I can plan to update it on our side.  Thanks again for you prompt attention.

- Justin

2019-02-25 23:49 UTC, datanotion commented
Hey there!  Yeah I'm interested in this too - it affecting us as well.  Thank you both for your help!

2019-02-26 14:11 UTC, PeterStaev commented
I will try to merge it sometime this week.

2019-02-26 20:49 UTC, merged

2019-02-26 20:50 UTC, datanotion commented
Awesome, thanks!

2019-02-26 22:35 UTC, PeterStaev commented
New version is now on NPM. Thank you for your contribution!

2019-02-26 22:41 UTC, socalrunner commented
My pleasure.  Thank you for pushing it out so quickly!

On Tue, Feb 26, 2019 at 2:35 PM Peter Staev <notifications@github.com>
wrote:

> New version is now on NPM. Thank you for your contribution!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PeterStaev/nativescript-image-swipe/pull/34#issuecomment-467642941>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AoU5-FEdVCBgXXTnIWcQ94_EBilgZsneks5vRba_gaJpZM4bGBEv>
> .
>